import classnames, {
  alignItems,
  backgroundColor,
  cursor,
  display,
  flexDirection,
  fontSize,
  fontStyle,
  fontWeight,
  gap,
  gridColumn,
  gridTemplateColumns,
  group,
  height,
  justifySelf,
  lineHeight,
  margin,
  maxWidth,
  opacity,
  overflow,
  position,
  textAlign,
  textTransform,
  transitionDuration,
  transitionProperty,
  width,
  zIndex,
} from "tailwindcss-classnames";

export const loadResearchStyles = () => ({
  wrapper: classnames(
    zIndex("z-10"),
    display("grid"),
    gridTemplateColumns("lg:grid-cols-5", "grid-cols-6"),
    gap("gap-2"),
  ),
  content: classnames(
    gridColumn("col-span-6", "lg:col-span-5"),
    margin("mb-20"),
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-center"),
    width("w-full"),
    maxWidth("md:max-w-sm", "max-w-full"),
    justifySelf("justify-self-center"),
  ),
  title: classnames(
    fontWeight("font-bold"),
    textTransform("uppercase"),
    lineHeight("leading-none"),
    fontSize("text-4xl"),
    "tracking-[-0.04em]" as any,
    "font-denton" as any,
  ),
  description: classnames(
    fontSize("text-sm"),
    fontStyle("italic"),
    opacity("opacity-50"),
  ),
  item: classnames(gridColumn("col-span-2", "lg:col-span-1"), height("h-full")),
  button: classnames(
    group("group"),
    display("block"),
    width("w-full"),
    cursor("cursor-pointer"),
    textAlign("text-left"),
  ),
  imageWrapper: classnames(
    position("relative"),
    overflow("overflow-hidden"),
    backgroundColor("bg-black"),
    transitionProperty("transition"),
    transitionDuration("duration-300"),
    "aspect-[4/5]" as any,
  ),
});
