import classnames, {
  alignItems,
  display,
  flexDirection,
  fontSize,
  fontWeight,
  gap,
  grayscale,
  gridColumn,
  gridTemplateColumns,
  group,
  inset,
  justifyContent,
  justifySelf,
  lineHeight,
  margin,
  maxWidth,
  opacity,
  overflow,
  padding,
  position,
  textTransform,
  transitionDuration,
  transitionProperty,
  translate,
  width,
} from "tailwindcss-classnames";

export const loadResearchStyles = () => ({
  wrapper: classnames(
    display("grid"),
    gridTemplateColumns("grid-cols-1", "lg:grid-cols-3", "sm:grid-cols-2"),
    gap("gap-2"),
    padding("px-2"),
  ),
  header: classnames(
    gridColumn("col-span-full"),
    margin("lg:mb-10", "mb-5"),
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-center"),
    width("w-full"),
    maxWidth("md:max-w-sm", "max-w-full"),
    justifySelf("justify-self-center"),
    "[&>span]:text-sm" as any,
    "[&>span]:italic" as any,
    "[&>span]:opacity-50" as any,
  ),
  pageTitle: classnames(
    fontSize("text-4xl"),
    textTransform("uppercase"),
    lineHeight("leading-none"),
    "font-denton" as any,
    "tracking-[-0.04em]" as any,
  ),
  cardWrapper: classnames(group("group")),
  content: classnames(
    position("relative"),
    overflow("overflow-hidden"),
    "aspect-[4/2.65]" as any,
  ),
  image: classnames(
    transitionProperty("transition-all"),
    transitionDuration("duration-500"),
    grayscale("group-hover:grayscale-0"),
    "group-hover:scale-[1.025]" as any,
  ),
  overlay: classnames(
    position("absolute"),
    inset("inset-0"),
    opacity("opacity-0", "group-hover:opacity-100"),
    transitionDuration("duration-300"),
    transitionProperty("transition-opacity"),
    "bg-black/50" as any,
  ),
  textContent: classnames(
    position("absolute"),
    inset("inset-0"),
    display("flex"),
    flexDirection("flex-col"),
    justifyContent("justify-between"),
    padding("p-3", "md:p-4"),
    transitionDuration("duration-300"),
    transitionProperty("transition-opacity"),
    opacity("opacity-0", "group-hover:opacity-100"),
    "text-color-arnecke-white" as any,
  ),
  year: classnames(
    opacity("opacity-70"),
    "text-[10px]" as any,
    "tracking-[0.18em]" as any,
    "font-systemia" as any,
  ),
  title: classnames(
    fontSize("text-2xl"),
    textTransform("uppercase"),
    overflow("overflow-hidden"),
    "font-denton" as any,
    "leading-[0.9]" as any,
    "tracking-[-0.03em]" as any,
  ),
  description: classnames(
    margin("mt-2"),
    overflow("overflow-hidden"),
    textTransform("uppercase"),
    "max-h-[44px]" as any,
    "font-helvetica" as any,
    "text-[10px]" as any,
    "leading-[1.45]" as any,
    "tracking-[0.14em]" as any,
  ),
  bottomContent: classnames(
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-between"),
    fontWeight("font-semibold"),
    textTransform("uppercase"),
    "font-helvetica" as any,
    "text-[10px]" as any,
    "tracking-[0.04em]" as any,
  ),
  research: classnames(
    display("flex"),
    alignItems("items-center"),
    overflow("overflow-hidden"),
    gap("gap-1"),
  ),
  arrow: classnames(
    translate("translate-x-4", "group-hover:translate-x-0"),
    opacity("opacity-0", "group-hover:opacity-100"),
    transitionDuration("duration-300"),
    transitionProperty("transition-all"),
  ),
});
