import classnames, {
  alignItems,
  borderColor,
  borderWidth,
  cursor,
  display,
  flex,
  flexDirection,
  flexShrink,
  fontSize,
  fontStyle,
  fontWeight,
  gap,
  height,
  inset,
  justifyContent,
  lineHeight,
  margin,
  objectFit,
  opacity,
  overflow,
  padding,
  pointerEvents,
  position,
  textAlign,
  textDecoration,
  textTransform,
  touchAction,
  userSelect,
  width,
  zIndex,
} from "tailwindcss-classnames";

export const loadContactCardStyles = () => ({
  wrapper: classnames(
    display("flex"),
    width("w-full"),
    flexDirection("flex-col"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    overflow("overflow-hidden"),
    padding("px-4"),
    "min-h-[70svh]" as any,
  ),
  content: classnames(
    position("relative"),
    width("w-full"),
    "aspect-[580/380]" as any,
    "max-w-[580px]" as any,
  ),
  motion: classnames(
    position("relative"),
    width("w-full"),
    height("h-full"),
    cursor("cursor-grab", "active:cursor-grabbing"),
    userSelect("select-none"),
    touchAction("touch-none"),
  ),
  cardContent: classnames(
    position("absolute"),
    inset("inset-0"),
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    overflow("overflow-hidden"),
    "bg-color-arnecke-white" as any,
    "text-color-arnecke-black" as any,
  ),
  frontWrapper: classnames(
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-center"),
    height("h-full"),
    justifyContent("justify-between"),
    padding("py-2", "sm:py-3"),
  ),
  title: classnames(
    textAlign("text-center"),
    fontWeight("font-semibold"),
    textTransform("uppercase"),
    fontStyle("italic"),
    lineHeight("leading-none"),
    "text-[clamp(24px,7vw,43px)]" as any,
    "font-helvetica" as any,
  ),
  descriptionWrapper: classnames(
    margin("mt-2", "sm:mt-4"),
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-center"),
  ),
  firstTextCopy: classnames(
    textTransform("uppercase"),
    lineHeight("leading-none"),
    "text-color-arnecke-black" as any,
    "text-[clamp(15px,4.8vw,30px)]" as any,
    "font-helvetica" as any,
  ),
  secondTextCopy: classnames(
    textTransform("uppercase"),
    lineHeight("leading-none"),
    "font-denton" as any,
    "text-color-arnecke-black" as any,
    "text-[clamp(68px,23vw,140px)]" as any,
  ),
  logoFront: classnames(height("h-auto"), "w-[clamp(54px,14vw,75px)]" as any),
  backWrapper: classnames(
    position("relative"),
    height("h-full"),
    width("w-full"),
    overflow("overflow-hidden"),
    padding("p-3", "sm:p-5"),
  ),
  bgImage: classnames(
    pointerEvents("pointer-events-none"),
    position("absolute"),
    inset("inset-0"),
    objectFit("object-cover", "sm:object-none"),
  ),
  linksWrapper: classnames(
    position("relative"),
    zIndex("z-10"),
    display("flex"),
    flexDirection("flex-col"),
    height("h-full"),
    justifyContent("justify-between"),
    fontWeight("font-light"),
    "font-helvetica" as any,
  ),
  links: classnames(
    display("flex"),
    flexDirection("flex-col", "sm:flex-row"),
    gap("gap-1"),
    fontStyle("italic"),
    lineHeight("leading-none"),
    justifyContent("sm:justify-between"),
    fontSize("sm:text-sm"),
    "text-[10px]" as any,
  ),
  link: classnames(
    position("relative"),
    zIndex("z-20"),
    pointerEvents("pointer-events-auto"),
    textDecoration("hover:underline"),
  ),
  backLogoWrapper: classnames(
    display("flex"),
    width("w-full"),
    alignItems("items-end"),
  ),
  border: classnames(
    flex("flex-1"),
    borderWidth("border-t-2"),
    borderColor("border-black"),
  ),
  backLogo: classnames(
    height("h-auto"),
    flexShrink("shrink-0"),
    "w-[clamp(54px,14vw,75px)]" as any,
  ),
  dragToRotate: classnames(
    margin("mt-6"),
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    gap("gap-2"),
    opacity("opacity-60"),
    textTransform("uppercase"),
    "font-systemia" as any,
    "text-[8px]" as any,
    "tracking-[0.22em]" as any,
  ),
});
