import classnames, {
  alignItems,
  backgroundColor,
  borderWidth,
  cursor,
  display,
  flexDirection,
  group,
  height,
  inset,
  justifyContent,
  lineHeight,
  margin,
  opacity,
  overflow,
  padding,
  pointerEvents,
  position,
  scale,
  textColor,
  textTransform,
  transformOrigin,
  transitionDuration,
  transitionProperty,
  transitionTimingFunction,
  width,
  zIndex,
} from "tailwindcss-classnames";

export const loadLanguageDropdownStyles = () => ({
  wrapper: classnames(
    position("relative"),
    zIndex("z-50"),
    width("w-fit"),
    "font-systemia" as any,
  ),
  globeWrapper: classnames(
    group("group"),
    position("relative"),
    display("flex"),
    height("h-8"),
    width("w-8"),
    cursor("cursor-pointer"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    textColor("text-current"),
    transitionProperty("transition-all"),
    transitionDuration("duration-300"),
    transitionTimingFunction("ease-in-out"),
    opacity("hover:opacity-75"),
    "active:scale-120" as any,
  ),
  globe: classnames(
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    transitionProperty("transition-transform"),
    transitionDuration("duration-300"),
    transitionTimingFunction("ease-in-out"),
  ),
  flag: classnames(
    position("absolute"),
    inset("bottom-0", "right-0"),
    display("flex"),
    height("h-4"),
    width("w-4"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    lineHeight("leading-none"),
    backgroundColor("bg-transparent"),
    "text-[10px]" as any,
  ),
  dropdownWrapper: (isOpen: boolean) =>
    classnames(
      position("absolute"),
      inset("right-0"),
      margin("mt-2"),
      display("flex"),
      width("w-16"),
      flexDirection("flex-col"),
      overflow("overflow-hidden"),
      borderWidth("border"),
      transitionProperty("transition-all"),
      transitionDuration("duration-300"),
      transformOrigin("origin-top-right"),
      "border-[#0200F7]" as any,
      "bg-color-arnecke-white" as any,
      "text-color-arnecke-blue" as any,
      "shadow-[0_8px_18px_rgba(0,0,0,0.12)]" as any,
      "ease-[cubic-bezier(0.16,1,0.3,1)]" as any,
      isOpen
        ? classnames(
            pointerEvents("pointer-events-auto"),
            scale("scale-100"),
            opacity("opacity-100"),
          )
        : classnames(
            pointerEvents("pointer-events-none"),
            scale("scale-95"),
            opacity("opacity-0"),
          ),
    ),
  optionWrapper: (isSelected: boolean) =>
    classnames(
      display("flex"),
      height("h-8"),
      width("w-full"),
      cursor("cursor-pointer"),
      alignItems("items-center"),
      justifyContent("justify-between"),
      padding("px-2"),
      textTransform("uppercase"),
      lineHeight("leading-none"),
      transitionProperty("transition-colors"),
      transitionDuration("duration-200"),
      transitionTimingFunction("ease-out"),
      "text-[8px]" as any,
      "tracking-[0.12em]" as any,
      "hover:bg-color-arnecke-blue" as any,
      "hover:text-color-arnecke-white" as any,
      isSelected
        ? classnames(
            "bg-color-arnecke-blue" as any,
            "text-color-arnecke-white" as any,
          )
        : classnames(
            "bg-color-arnecke-white" as any,
            "text-color-arnecke-blue" as any,
          ),
    ),
  flagDropdown: classnames(lineHeight("leading-none"), "text-[14px]" as any),
});
