import classnames, {
  alignItems,
  aspectRatio,
  borderColor,
  borderWidth,
  cursor,
  display,
  flexDirection,
  gap,
  gridColumn,
  height,
  inset,
  justifyContent,
  margin,
  minHeight,
  objectFit,
  opacity,
  overflow,
  padding,
  pointerEvents,
  position,
  transitionProperty,
  width,
} from "tailwindcss-classnames";

export const loadModalContentStyles = () => ({
  rightWrapper: classnames(gridColumn("col-span-12", "md:col-span-5")),
  rightContent: classnames(
    display("flex"),
    flexDirection("flex-col"),
    justifyContent("justify-center"),
    gap("gap-3", "md:gap-4"),
  ),
  images: classnames(
    position("relative"),
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    height("md:h-auto"),
    overflow("overflow-hidden"),
    padding("p-3", "md:p-5"),
    aspectRatio("md:aspect-square"),
    "h-[34vh]" as any,
  ),
  image: classnames(
    height("h-full"),
    width("w-full"),
    objectFit("object-contain"),
    "max-w-[320px]" as any,
    "grayscale-[8%]" as any,
    "md:max-h-[50vh]" as any,
    "md:max-w-[400px]" as any,
  ),
  buttons: classnames(
    pointerEvents("pointer-events-none"),
    position("absolute"),
    inset("inset-x-0", "top-1/2"),
    display("flex"),
    justifyContent("justify-between"),
    "-translate-y-1/2" as any,
  ),
  button: classnames(
    pointerEvents("pointer-events-auto"),
    display("flex"),
    alignItems("items-center"),
    height("h-9"),
    width("w-9"),
    justifyContent("justify-center"),
    cursor("cursor-pointer"),
    "text-color-arnecke-blue" as any,
  ),
  bottomRightContent: classnames(
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-between"),
    gap("gap-2"),
    "[&>span]:text-[10px]" as any,
    "[&>span]:uppercase" as any,
    "[&>span]:tracking-[0.28em]" as any,
    "[&>span]:text-color-arnecke-blue" as any,
  ),
  tinyImagesBottom: classnames(
    display("flex"),
    alignItems("items-center"),
    gap("gap-2"),
  ),
  tinyImageWrapper: (selectedImageIndex: number, index: number) => {
    const isSelected = selectedImageIndex === index;
    return classnames(
      height("h-8", "md:h-10"),
      width("w-7", "md:w-8"),
      cursor("cursor-pointer"),
      overflow("overflow-hidden"),
      borderWidth("border"),
      transitionProperty("transition-all"),
      isSelected
        ? ("border-color-arnecke-blue" as any)
        : borderColor("border-transparent"),
      isSelected ? opacity("opacity-100") : opacity("opacity-40"),
      !isSelected ? opacity("hover:opacity-80") : undefined,
    );
  },
  tinyImage: classnames(
    height("h-full"),
    width("w-full"),
    objectFit("object-cover"),
  ),
  leftWrapper: classnames(gridColumn("col-span-12", "md:col-span-7")),
  leftContent: classnames(
    height("h-full"),
    display("flex"),
    justifyContent("justify-start"),
    minHeight("min-h-0"),
    flexDirection("flex-col"),
    padding("md:pl-3"),
  ),
  bottomLeftContent: classnames(
    margin("md:mt-auto", "mt-4"),
    display("flex"),
    justifyContent("justify-between"),
    gap("gap-4"),
    borderWidth("border-t"),
    padding("pt-2"),
    "border-color-arnecke-blue" as any,
  ),
  bottomLeftItem: classnames(
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-start"),
    "[&>span]:mb-1" as any,
    "[&>span]:text-[11px] " as any,
    "[&>span]:uppercase" as any,
    "[&>span]:tracking-[0.24em]" as any,
    "[&>span]:text-color-arnecke-blue" as any,
    "[&>span]:opacity-80" as any,
    "[&>p]:text-[10px]" as any,
    "[&>a]:text-[10px]" as any,
    "[&>p]:opacity-70" as any,
    "[&>a]:opacity-70" as any,
  ),
});
