import classnames, {
  alignItems,
  cursor,
  display,
  flexDirection,
  fontSize,
  gap,
  height,
  inset,
  margin,
  opacity,
  padding,
  position,
  textAlign,
  textTransform,
  transitionDuration,
  transitionProperty,
  translate,
  width,
} from "tailwindcss-classnames";

export const loadFooterStyles = () => ({
  wrapper: classnames(
    width("w-full"),
    padding("px-5", "py-10"),
    margin("mx-auto"),
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-center"),
    textAlign("text-center"),
    gap("gap-6"),
    "bg-color-arnecke-blue" as any,
    "text-color-arnecke-white" as any,
    "font-helvetica" as any,
    "max-w-[700px]" as any,
  ),
  logo: classnames("invert" as any),
  nav: classnames(
    display("flex"),
    alignItems("items-center"),
    gap("gap-4"),
    textTransform("uppercase"),
    fontSize("text-sm"),
  ),
  archiveButton: classnames(
    cursor("cursor-pointer"),
    transitionProperty("transition-opacity"),
    textTransform("uppercase"),
    opacity("hover:opacity-60"),
  ),
  socialLink: classnames(
    display("flex"),
    alignItems("items-center"),
    gap("gap-2"),
    transitionProperty("transition-opacity"),
    opacity("hover:opacity-60"),
  ),
  shopLink: classnames(
    transitionProperty("transition-opacity"),
    opacity("hover:opacity-60"),
  ),
  divider: classnames(width("w-full"), height("h-px"), "bg-white/10" as any),
  credits: classnames(
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-center"),
    gap("gap-1"),
    "text-[11px]" as any,
    "text-white/50" as any,
  ),
  creditLink: classnames(
    transitionProperty("transition-colors"),
    "text-white/80" as any,
    "hover:text-white" as any,
  ),

  archiveOverlay: (isArchiveOpen: boolean) =>
    classnames(
      position("fixed"),
      inset("inset-0"),
      transitionDuration("duration-300"),
      transitionProperty("transition-transform"),
      "z-[100]" as any,
      "transform" as any,
      "ease-in-out" as any,
      isArchiveOpen
        ? translate("translate-y-0")
        : translate("translate-y-full"),
    ),
});
