import classnames, {
  alignItems,
  display,
  flexDirection,
  fontSize,
  justifySelf,
  lineHeight,
  margin,
  textAlign,
  textTransform,
  width,
} from "tailwindcss-classnames";

export const loadResearchSubpageStyles = () => ({
  titleContent: classnames(
    margin("mb-5"),
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-center"),
    width("w-full"),
    justifySelf("justify-self-center"),
    "[&>span]:text-lg" as any,
    "[&>span]:italic" as any,
    "[&>span]:opacity-50" as any,
    "text-color-arnecke-black" as any,
    "[&>span]:text-center" as any,
  ),
  title: classnames(
    textTransform("uppercase"),
    lineHeight("leading-none"),
    fontSize("md:text-[66px]" as any, "text-4xl"),
    "tracking-[-0.04em]" as any,
    "font-denton" as any,
  ),
  article: classnames(
    fontSize("text-base", "md:text-lg"),
    lineHeight("leading-8"),
    textAlign("text-justify"),
    "text-color-arnecke-black" as any,
    "[&_p]:mb-6" as any,
    "[&_a]:text-color-arnecke-blue" as any,
    "[&_a]:underline" as any,
    "[&_a]:underline-offset-4" as any,
    "[&_a]:transition-opacity" as any,
    "[&_a:hover]:opacity-70" as any,
    "[&_hr]:my-10" as any,
    "[&_hr]:border-0" as any,
    "[&_hr]:border-t" as any,
    "[&_hr]:border-color-arnecke-black" as any,
    "[&_hr]:opacity-30" as any,
    "[&_img]:my-10" as any,
    "[&_img]:max-w-full" as any,
    "[&_div]:max-w-full" as any,
  ),
});
