import classnames, {
  cursor,
  inset,
  lineHeight,
  listStyleType,
  margin,
  overflow,
  overscrollBehavior,
  padding,
  pointerEvents,
  position,
  textTransform,
  transitionDuration,
  transitionProperty,
  transitionTimingFunction,
  width,
} from "tailwindcss-classnames";

export const loadScreenMenuStyles = () => ({
  wrapper: classnames(
    textTransform("uppercase"),
    position("fixed"),
    inset("inset-0"),
    pointerEvents("pointer-events-auto"),
    overscrollBehavior("overscroll-contain"),
    overflow("overflow-y-auto", "overflow-x-hidden"),
    "font-systemia" as any,
    "z-[999]" as any,
    "bg-color-arnecke-white" as any,
    "h-dvh" as any,
    "[-webkit-overflow-scrolling:touch]" as any,
  ),
  closeButton: classnames(
    position("fixed"),
    inset("top-0", "right-0"),
    cursor("cursor-pointer"),
    transitionProperty("transition-opacity"),
    "z-[1000]" as any,
    "hover:opacity-50" as any,
  ),
  menuList: classnames(
    margin("mt-14"),
    padding("p-0", "pb-10"),
    listStyleType("list-none"),
  ),
  listItem: classnames(
    padding("p-0"),
    width("w-fit"),
    cursor("cursor-pointer"),
    transitionProperty("transition-colors"),
    transitionDuration("duration-200"),
    transitionTimingFunction("ease-in-out"),
    lineHeight("md:leading-25" as any, "leading-10" as any),
    "md:text-[7.8vw]" as any,
    "text-[40px]" as any,
    "text-color-arnecke-black" as any,
    "hover:!text-[#0200F7]" as any,
  ),
});
