import classnames, {
  alignItems,
  backgroundColor,
  cursor,
  display,
  flexDirection,
  fontSize,
  fontWeight,
  gap,
  gridColumn,
  gridTemplateColumns,
  height,
  inset,
  justifyContent,
  justifySelf,
  lineHeight,
  margin,
  maxWidth,
  objectFit,
  opacity,
  overflow,
  position,
  textTransform,
  transitionDuration,
  transitionProperty,
  width,
  zIndex,
} from "tailwindcss-classnames";

export const loadPageStyles = () => ({
  wrapper: classnames(
    zIndex("z-10"),
    display("grid"),
    gridTemplateColumns("grid-cols-3", "lg:grid-cols-5"),
    gap("gap-2"),
  ),
  titleContent: classnames(
    gridColumn("col-span-3", "lg:col-span-5"),
    margin("lg:mb-20", "mb-5"),
    display("flex"),
    flexDirection("flex-col"),
    alignItems("items-center"),
    width("w-full"),
    maxWidth("md:max-w-sm", "max-w-full"),
    justifySelf("justify-self-center"),
    "[&>span]:text-sm" as any,
    "[&>span]:italic" as any,
    "[&>span]:opacity-50" as any,
  ),
  title: classnames(
    fontWeight("font-bold"),
    textTransform("uppercase"),
    lineHeight("leading-none"),
    fontSize("text-4xl"),
    "tracking-[-0.04em]" as any,
    "font-denton" as any,
  ),
  imageWrapper: (borderedItems: boolean, squaredImages: boolean) =>
    classnames(
      "group" as any,
      cursor("cursor-pointer"),
      position("relative"),
      overflow("overflow-hidden"),
      squaredImages && ("aspect-square" as any),
      borderedItems && ("border-1" as any),
      borderedItems && ("border-transparent" as any),
      borderedItems && ("hover:border-[#0200F7]" as any),
    ),
  imageHoverOverlay: classnames(
    position("absolute"),
    inset("inset-0"),
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    opacity("opacity-0"),
    transitionProperty("transition-opacity"),
    transitionDuration("duration-300"),
    "bg-black/40" as any,
    "text-color-arnecke-white" as any,
    "group-hover:opacity-100" as any,
    "pointer-events-none" as any,
    "[&>span]:font-systemia" as any,
    "[&>span]:uppercase" as any,
    "[&>span]:text-[8px]" as any,
    "[&>span]:tracking-[0.24em]" as any,
    "[&>span]:mt-auto" as any,
    "[&>span]:p-2" as any,
  ),
  image: classnames(
    height("h-full"),
    width("w-full"),
    objectFit("object-cover"),
  ),
});
