import classnames, {
  alignItems,
  backdropBlur,
  borderRadius,
  cursor,
  display,
  gap,
  height,
  inset,
  justifyContent,
  objectFit,
  opacity,
  overflow,
  padding,
  position,
  textColor,
  transitionDuration,
  transitionProperty,
  width,
  zIndex,
} from "tailwindcss-classnames";

export const loadCircleNumbersStyles = () => ({
  wrapperVideo: classnames(
    position("relative"),
    height("h-full"),
    width("w-full"),
    overflow("overflow-hidden"),
  ),
  video: classnames(
    height("h-full"),
    width("w-full"),
    objectFit("object-contain", "md:object-cover"),
  ),
  buttonWrapper: classnames(
    position("absolute"),
    inset("bottom-4", "right-4", "md:bottom-40"),
    zIndex("z-10"),
    display("flex"),
    gap("gap-2"),
    "-translate-x-1/2" as any,
  ),
  button: classnames(
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-center"),
    height("h-5", "md:h-auto"),
    width("w-5", "md:w-auto"),
    borderRadius("rounded-full"),
    cursor("cursor-pointer"),
    textColor("text-white"),
    transitionProperty("transition-opacity"),
    transitionDuration("duration-300"),
    padding("md:p-3"),
    opacity("opacity-70", "hover:opacity-100"),
    backdropBlur("backdrop-blur"),
    "bg-black/50" as any,
  ),
  pageWrapper: classnames(padding("pt-10")),
});
