import classnames, {
  alignItems,
  borderWidth,
  cursor,
  display,
  flexDirection,
  fontSize,
  fontWeight,
  gap,
  group,
  height,
  inset,
  justifyContent,
  lineHeight,
  margin,
  opacity,
  overflow,
  padding,
  position,
  rotate,
  textTransform,
  transformOrigin,
  transitionDuration,
  transitionProperty,
  translate,
  width,
  zIndex,
} from "tailwindcss-classnames";

export const loadHamburguerMenuStyles = () => ({
  buttonWrapper: classnames(
    cursor("cursor-pointer"),
    position("relative"),
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-start"),
    "z-[99]" as any,
  ),
  wrapper: (isMenuOpen: boolean) =>
    classnames(
      position("fixed"),
      inset("inset-0"),
      zIndex("z-40"),
      transitionDuration("duration-500"),
      height("h-screen"),
      width("w-full", "lg:w-1/3"),
      transitionProperty("transition-transform"),
      isMenuOpen ? translate("translate-x-0") : ("translate-x-[-100%]" as any),
      "bg-color-arnecke-blue" as any,
      "text-color-arnecke-white" as any,
      "ease-[cubic-bezier(0.77,0,0.18,1)]" as any,
    ),
  content: classnames(
    position("relative"),
    height("h-full"),
    width("w-full"),
    padding("px-5", "pb-6", "pt-16"),
    overflow("overflow-hidden"),
    "font-helvetica" as any,
  ),
  exploreText: classnames(
    position("absolute"),
    inset("top-4", "right-5"),
    textTransform("uppercase"),
    "text-[10px]" as any,
    "tracking-[0.35em]" as any,
    "text-white/50" as any,
  ),
  verticalText: classnames(
    position("absolute"),
    inset("bottom-7", "right-5"),
    textTransform("uppercase"),
    rotate("rotate-90"),
    transformOrigin("origin-bottom-right"),
    "text-[10px]" as any,
    "tracking-[0.35em]" as any,
    "text-white/40" as any,
  ),
  horizontalText: classnames(
    position("absolute"),
    inset("bottom-5", "left-10"),
    textTransform("uppercase"),
    "font-helvetica" as any,
    "text-[10px]" as any,
    "tracking-[0.25em]" as any,
    "text-white/40" as any,
  ),
  verticalLineRight: classnames(
    position("absolute"),
    inset("left-5"),
    width("w-px"),
    display("lg:block", "hidden"),
    "bg-white/20" as any,
    "top-[70px]" as any,
    "h-[calc(100%-100px)]" as any,
  ),
  verticalLineLeft: classnames(
    position("absolute"),
    inset("right-0"),
    width("w-px"),
    display("lg:block", "hidden"),
    "bg-white/20" as any,
    "top-[70px]" as any,
    "h-[calc(100%-100px)]" as any,
  ),
  listItem: classnames(
    borderWidth("border-t", "last:border-b"),
    margin("lg:ml-5"),
    "border-white/25" as any,
  ),
  listLink: classnames(
    group("group"),
    display("flex"),
    alignItems("items-center"),
    justifyContent("justify-between"),
    padding("py-5"),
    textTransform("uppercase"),
    cursor("cursor-pointer"),
    gap("gap-3"),
    fontSize("text-xl"),
    lineHeight("leading-none"),
    fontWeight("font-bold"),
    "tracking-[-0.05em]" as any,
  ),
  numberWrapper: classnames(
    opacity("group-hover:opacity-100"),
    opacity("opacity-40"),
    transitionProperty("transition-opacity"),
    fontWeight("font-normal"),
    "tracking-[0.3em]" as any,
    "text-[11px]" as any,
  ),
  socialWrapper: classnames(
    position("absolute"),
    inset("bottom-16", "left-10", "right-10"),
    display("flex"),
    flexDirection("flex-row"),
    alignItems("items-center"),
    gap("gap-2"),
  ),
  socialItem: classnames(
    opacity("opacity-70"),
    opacity("hover:opacity-100"),
    transitionProperty("transition-all"),
    transitionDuration("duration-300"),
  ),
  archiveWrapper: (isArchiveOpen: boolean) =>
    classnames(
      position("fixed"),
      inset("inset-0"),
      transitionDuration("duration-300"),
      transitionProperty("transition-transform"),
      "ease-in-out" as any,
      "z-[100]" as any,
      isArchiveOpen
        ? translate("translate-y-0")
        : translate("translate-y-full"),
    ),
});
